// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fluentd.proto

package proto_fluentd // import "github.com/synerex/proto_fluentd"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FluentdRecord struct {
	Tag                  string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Record               []byte               `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FluentdRecord) Reset()         { *m = FluentdRecord{} }
func (m *FluentdRecord) String() string { return proto.CompactTextString(m) }
func (*FluentdRecord) ProtoMessage()    {}
func (*FluentdRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fluentd_5ed57439f017966d, []int{0}
}
func (m *FluentdRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FluentdRecord.Unmarshal(m, b)
}
func (m *FluentdRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FluentdRecord.Marshal(b, m, deterministic)
}
func (dst *FluentdRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FluentdRecord.Merge(dst, src)
}
func (m *FluentdRecord) XXX_Size() int {
	return xxx_messageInfo_FluentdRecord.Size(m)
}
func (m *FluentdRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FluentdRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FluentdRecord proto.InternalMessageInfo

func (m *FluentdRecord) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *FluentdRecord) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *FluentdRecord) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterType((*FluentdRecord)(nil), "proto.fluentd.FluentdRecord")
}

func init() { proto.RegisterFile("fluentd.proto", fileDescriptor_fluentd_5ed57439f017966d) }

var fileDescriptor_fluentd_5ed57439f017966d = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0x29, 0x4d,
	0xcd, 0x2b, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0x53, 0x7a, 0x50, 0x41,
	0x29, 0xf9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0xb0, 0x68, 0x52, 0x69, 0x9a, 0x7e, 0x49,
	0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x01, 0x44, 0xbd, 0x52, 0x26, 0x17, 0xaf, 0x1b, 0x44,
	0x6d, 0x50, 0x6a, 0x72, 0x7e, 0x51, 0x8a, 0x90, 0x00, 0x17, 0x73, 0x49, 0x62, 0xba, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0xa4, 0xc7, 0xc5, 0x02, 0xd2, 0x25, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x6d, 0x24, 0xa5, 0x07, 0x31, 0x52, 0x0f, 0x66, 0xa4, 0x5e, 0x08, 0xcc, 0xc8, 0x20,
	0xb0, 0x3a, 0x21, 0x31, 0x2e, 0xb6, 0x22, 0xb0, 0x59, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41,
	0x50, 0x9e, 0x93, 0x52, 0x94, 0x42, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x7e, 0x71, 0x65, 0x5e, 0x6a, 0x51, 0x6a, 0x05, 0xc4, 0x65, 0xf1, 0x50, 0xf7, 0x26, 0xb1, 0x81,
	0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xdb, 0x55, 0x5f, 0xd6, 0x00, 0x00, 0x00,
}
